/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f6f58a91e8635d792b38ea4284e2c5b8)
interface __BaseEnv_Env {
	ADMIN_DB: D1Database;
	ASSETS: Fetcher;
	NEXT_PUBLIC_MAPBOX_TOKEN: string;
	RESEND_API_KEY: string;
	WORKER_SELF_REFERENCE: Fetcher /* pueblo-food-map-staging */ | Service<typeof import("./custom-worker").default>;
	HC_PING_URL?: "https://hc-ping.com/3d8c7693-8506-49d3-a4a4-d34426f3ea9a";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./custom-worker");
	}
	interface StagingEnv {
		ADMIN_DB: D1Database;
		ASSETS: Fetcher;
		NEXT_PUBLIC_MAPBOX_TOKEN: string;
		RESEND_API_KEY: string;
		WORKER_SELF_REFERENCE: Fetcher /* pueblo-food-map-staging */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_MAPBOX_TOKEN" | "RESEND_API_KEY" | "HC_PING_URL">> {}
}
