// Auto-generated by scripts/match-benefits.py — do not edit by hand.
//
// accepts_snap / accepts_wic flags for the OSM grocery/convenience/farm
// venues, matched (by name + location) against authoritative public data:
//   SNAP: USDA FNS SNAP Retailer Location data (Pueblo County, CO)
//   WIC:  CDPHE WIC Vendor Locations (city of Pueblo)
// Only confident matches are flagged (conservative — a benefits tool must
// not over-claim). Re-run the script to refresh; commit the diff.
//   SNAP: 49 stores   WIC: 8 stores   (of 60 retailers)

export const benefitFlags: Record<string, { snap: boolean; wic: boolean }> = {
  "osm-node-10239124452": { snap: true, wic: false },
  "osm-node-11550915644": { snap: true, wic: false },
  "osm-node-12079476149": { snap: true, wic: false },
  "osm-node-12184485110": { snap: true, wic: false },
  "osm-node-12199987090": { snap: true, wic: false },
  "osm-node-12259768973": { snap: true, wic: false },
  "osm-node-12478967185": { snap: true, wic: false },
  "osm-node-12496998446": { snap: true, wic: false },
  "osm-node-12528946501": { snap: true, wic: false },
  "osm-node-12599529644": { snap: true, wic: false },
  "osm-node-12599529663": { snap: true, wic: false },
  "osm-node-12839229515": { snap: true, wic: false },
  "osm-node-12849787149": { snap: true, wic: false },
  "osm-node-13398740836": { snap: true, wic: false },
  "osm-node-4041145706": { snap: true, wic: false },
  "osm-node-4041363143": { snap: true, wic: false },
  "osm-node-4041363163": { snap: true, wic: false },
  "osm-node-4041375005": { snap: true, wic: false },
  "osm-node-4041375052": { snap: true, wic: false },
  "osm-node-4043068526": { snap: true, wic: false },
  "osm-node-4043068646": { snap: true, wic: false },
  "osm-node-5409829684": { snap: true, wic: false },
  "osm-way-1079237907": { snap: true, wic: false },
  "osm-way-224603771": { snap: true, wic: false },
  "osm-way-264728293": { snap: true, wic: false },
  "osm-way-439892311": { snap: true, wic: false },
  "osm-way-439892313": { snap: true, wic: true },
  "osm-way-466464064": { snap: true, wic: false },
  "osm-way-499816958": { snap: true, wic: false },
  "osm-way-505568940": { snap: true, wic: false },
  "osm-way-535378000": { snap: true, wic: false },
  "osm-way-535379543": { snap: true, wic: false },
  "osm-way-535650928": { snap: true, wic: false },
  "osm-way-535656814": { snap: true, wic: false },
  "osm-way-535686236": { snap: true, wic: false },
  "osm-way-536454112": { snap: true, wic: true },
  "osm-way-544400971": { snap: true, wic: true },
  "osm-way-547529779": { snap: true, wic: false },
  "osm-way-591851971": { snap: true, wic: false },
  "osm-way-659620782": { snap: true, wic: false },
  "osm-way-682492454": { snap: true, wic: true },
  "osm-way-682492473": { snap: true, wic: true },
  "osm-way-946612229": { snap: true, wic: true },
  "osm-way-946612238": { snap: true, wic: true },
  "osm-way-946614791": { snap: true, wic: false },
  "osm-way-946614803": { snap: true, wic: true },
  "osm-way-947245256": { snap: true, wic: false },
  "osm-way-971896407": { snap: true, wic: false },
  "osm-way-974172860": { snap: true, wic: false },
};
