/**
 * published-venues.ts — auto-generated by POST /api/admin/publish (#237).
 * DO NOT hand-edit — the next publish overwrites this file entirely.
 *
 * Source of truth is Cloudflare D1 (`pueblo-food-map-admin`.venues); this
 * file is the build-time snapshot the public map imports at request time
 * (docs/admin/cloudflare-native-admin-spec.md §3.3, §3.5 step 3).
 * Last published: 2026-07-22T03:27:10.031Z
 */
import type { Venue } from "@/types/venue";

export const publishedVenues: Venue[] = [
  {
    "id": "garden-bethany-lutheran",
    "name": "Bethany Lutheran Church Garden",
    "category": "garden",
    "lat": 38.297496,
    "lng": -104.591039,
    "address": "1802 Sheridan Rd, Pueblo, CO 81001",
    "email": "garden@pueblofoodproject.org",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Open to public. Produce donated to food pantries. Partner: Pueblo County Extension Master Gardener Program.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "garden-la-familia",
    "name": "La Familia Community Garden",
    "category": "garden",
    "lat": 38.271769,
    "lng": -104.596439,
    "address": "814 E 5th St, Pueblo, CO 81001",
    "email": "garden@pueblofoodproject.org",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Open to public. Produce donated to food pantries. Partner: Pueblo County Extension Master Gardener Program.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "garden-midway",
    "name": "Midway Community Garden",
    "category": "garden",
    "lat": 38.260521,
    "lng": -104.621467,
    "address": "110 Midway Dr, Pueblo, CO",
    "email": "garden@pueblofoodproject.org",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Open to public. Produce donated to food pantries. Partner: Pueblo County Extension Master Gardener Program.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "garden-ray-aguilera",
    "name": "Ray Aguilera Community Garden",
    "category": "garden",
    "lat": 38.23117,
    "lng": -104.625036,
    "address": "Lake Ave near the Fire Station, Pueblo, CO",
    "email": "garden@pueblofoodproject.org",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Open to public. Produce donated to food pantries. Partner: Pueblo County Extension Master Gardener Program.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "garden-rmser",
    "name": "RMSER Community Garden",
    "category": "garden",
    "lat": 38.254427,
    "lng": -104.620381,
    "address": "330 Lake Ave, Pueblo, CO 81004",
    "hours_weekly": {
      "wed": [
        "16:00-19:00"
      ]
    },
    "email": "garden@pueblofoodproject.org",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Weekly volunteer work days Wed 4-7pm. Produce donated to food pantries. Partner: Pueblo County Extension Master Gardener Program.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "garden-steelworks",
    "name": "Steelworks Museum Garden",
    "category": "garden",
    "lat": 38.237869,
    "lng": -104.612428,
    "address": "215 Canal St, Pueblo, CO 81004",
    "email": "garden@pueblofoodproject.org",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Open to public. Produce donated to food pantries. Partner: Pueblo County Extension Master Gardener Program.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "landscape-central-plaza",
    "name": "Central Plaza Edible Landscape",
    "category": "edible_landscape",
    "lat": 38.268172,
    "lng": -104.608897,
    "address": "1st & Main, Pueblo, CO",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Public edible landscape installation in downtown Pueblo.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "landscape-fuel-iron",
    "name": "Fuel & Iron Edible Landscape",
    "category": "edible_landscape",
    "lat": 38.262121,
    "lng": -104.615912,
    "address": "400 S Union Ave, Pueblo, CO 81003",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Edible landscape at Pueblo's first food hall.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "landscape-jj-raigoza",
    "name": "JJ Raigoza Park Edible Landscape",
    "category": "edible_landscape",
    "lat": 38.222062,
    "lng": -104.617207,
    "address": "600 Maryland Ave, Pueblo, CO",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Public edible landscape installation.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "landscape-mineral-palace",
    "name": "Mineral Palace Park Edible Landscape",
    "category": "edible_landscape",
    "lat": 38.283229,
    "lng": -104.607842,
    "address": "Mineral Palace Park, Pueblo, CO",
    "url": "https://pueblofoodproject.org/cgsp/",
    "notes": "Public edible landscape installation.",
    "operator": "Pueblo Food Project",
    "source": "pueblofoodproject.org/cgsp",
    "last_verified": "2026-05-12"
  },
  {
    "id": "manual-c96265c3-cfed-46ff-b880-a8d6fe437e88",
    "name": "Pueblo Farmer's Market",
    "category": "farm",
    "lat": 38.283714414530714,
    "lng": -104.60580025592952,
    "address": "Mineral Palace Park",
    "hours_weekly": {
      "mon": [
        "0"
      ],
      "sat": [
        "0730-1200"
      ]
    },
    "accepts_snap": true,
    "url": "https://www.pueblofarmersmarket.org",
    "notes": "The Market is occasionally at different locations (East Side Pueblo Community Health Center parking lot) or has special events. Please refer to their website for the most up to date locations and events.",
    "operator": "Marcy",
    "source": "Manual entry",
    "last_verified": "2026-07-22"
  },
  {
    "id": "osm-node-10239124452",
    "name": "Sinclair",
    "category": "convenience",
    "lat": 38.274672,
    "lng": -104.496445,
    "address": "Baxter Road, Baxter, CO 81006",
    "source": "OpenStreetMap (node/10239124452)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-11550915644",
    "name": "Baguni Mart",
    "category": "grocery",
    "lat": 38.309201,
    "lng": -104.621343,
    "address": "Club Manor Drive, Pueblo, CO 81008",
    "source": "OpenStreetMap (node/11550915644)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12079476149",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.245151,
    "lng": -104.57943,
    "address": "South Aspen Road, Blende, CO 81003",
    "source": "OpenStreetMap (node/12079476149)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12184485110",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.236852,
    "lng": -104.349524,
    "address": "US 50 Business, Avondale, CO 81022",
    "source": "OpenStreetMap (node/12184485110)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12199987090",
    "name": "7-Eleven",
    "category": "convenience",
    "lat": 38.244527,
    "lng": -104.621195,
    "address": "West Northern Avenue, Pueblo, CO 81004",
    "source": "OpenStreetMap (node/12199987090)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12259768973",
    "name": "Alta Convenience",
    "category": "convenience",
    "lat": 38.24358,
    "lng": -104.614027,
    "address": "East Abriendo Avenue, Pueblo, CO 81004",
    "source": "OpenStreetMap (node/12259768973)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12478967185",
    "name": "7-Eleven",
    "category": "convenience",
    "lat": 38.274691,
    "lng": -104.611215,
    "address": "West 8th Street, Pueblo, CO 81003",
    "source": "OpenStreetMap (node/12478967185)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12496998446",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.282973,
    "lng": -104.624074,
    "address": "Francisco Street, Pueblo, CO 81002",
    "source": "OpenStreetMap (node/12496998446)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12528946501",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.245112,
    "lng": -104.565459,
    "address": "20th Lane, Blende, CO 81006",
    "source": "OpenStreetMap (node/12528946501)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12599529644",
    "name": "Mauro Farms Market & Bakery",
    "category": "farm",
    "lat": 38.249815,
    "lng": -104.458242,
    "address": "936 36th Lane, Pueblo, CO 81006",
    "hours_weekly": {
      "mon": [
        "09:00-16:00"
      ],
      "tue": [
        "09:00-16:00"
      ],
      "wed": [
        "09:00-16:00"
      ],
      "thu": [
        "09:00-16:00"
      ],
      "fri": [
        "09:00-16:00"
      ],
      "sat": [
        "09:00-16:00"
      ],
      "sun": [
        "09:00-16:00"
      ]
    },
    "accepts_snap": true,
    "phone": "+1 719-948-3381",
    "url": "https://maurofarms.com/",
    "notes": "Identifies as Women owned",
    "source": "OpenStreetMap (node/12599529644)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12599529663",
    "name": "DiTomaso Farms",
    "category": "farm",
    "lat": 38.245356,
    "lng": -104.448073,
    "address": "37137 US 50 Bus, Pueblo, CO 81006",
    "hours_weekly": {
      "mon": [
        "08:00-17:00"
      ],
      "tue": [
        "08:00-17:00"
      ],
      "wed": [
        "08:00-17:00"
      ],
      "thu": [
        "08:00-17:00"
      ],
      "fri": [
        "08:00-17:00"
      ],
      "sat": [
        "08:00-17:00"
      ],
      "sun": [
        "08:00-17:00"
      ]
    },
    "phone": "+1 719-948-3200",
    "url": "https://www.facebook.com/ditomasofarms1/",
    "source": "OpenStreetMap (node/12599529663)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12706112997",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.253695,
    "lng": -104.662294,
    "address": "Lucille Street, Pueblo, CO 81005",
    "source": "OpenStreetMap (node/12706112997)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12839229515",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.245728,
    "lng": -104.458933,
    "address": "36th Lane, Vineland, CO",
    "source": "OpenStreetMap (node/12839229515)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-12849787149",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.306105,
    "lng": -104.599331,
    "address": "Montebello Road, Pueblo, CO 81008",
    "source": "OpenStreetMap (node/12849787149)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-13398740836",
    "name": "Murphy USA",
    "category": "convenience",
    "lat": 38.238409,
    "lng": -104.663068,
    "address": "Glenroyal Drive, Pueblo, CO 81005",
    "source": "OpenStreetMap (node/13398740836)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4041145706",
    "name": "Alta Convenience",
    "category": "convenience",
    "lat": 38.270767,
    "lng": -104.586859,
    "address": "North Monument Avenue, Pueblo, CO 81001",
    "source": "OpenStreetMap (node/4041145706)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4041297300",
    "name": "Shell",
    "category": "convenience",
    "lat": 38.309138,
    "lng": -104.631284,
    "address": "Kachina Drive, Pueblo, CO 81008",
    "source": "OpenStreetMap (node/4041297300)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4041363143",
    "name": "Mindful Food",
    "category": "convenience",
    "lat": 38.224792,
    "lng": -104.625627,
    "address": "Iowa Avenue, Pueblo, CO 81004",
    "source": "OpenStreetMap (node/4041363143)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4041363156",
    "name": "Western Convenience Store",
    "category": "convenience",
    "lat": 38.218303,
    "lng": -104.625608,
    "address": "3201 Lake Avenue, Pueblo, CO 81004",
    "hours_weekly": {
      "mon": [
        "00:00-24:00"
      ],
      "tue": [
        "00:00-24:00"
      ],
      "wed": [
        "00:00-24:00"
      ],
      "thu": [
        "00:00-24:00"
      ],
      "fri": [
        "00:00-24:00"
      ],
      "sat": [
        "00:00-24:00"
      ],
      "sun": [
        "00:00-24:00"
      ]
    },
    "operator": "Western Convenience Store",
    "source": "OpenStreetMap (node/4041363156)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4041363163",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.26624,
    "lng": -104.628526,
    "address": "West 4th Street, Pueblo, CO 81002",
    "source": "OpenStreetMap (node/4041363163)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4041374999",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.219356,
    "lng": -104.625713,
    "address": "1201 West Pueblo Boulevard, Pueblo, CO 81004",
    "hours_weekly": {
      "mon": [
        "00:00-24:00"
      ],
      "tue": [
        "00:00-24:00"
      ],
      "wed": [
        "00:00-24:00"
      ],
      "thu": [
        "00:00-24:00"
      ],
      "fri": [
        "00:00-24:00"
      ],
      "sat": [
        "00:00-24:00"
      ],
      "sun": [
        "00:00-24:00"
      ]
    },
    "operator": "Loaf 'N Jug",
    "source": "OpenStreetMap (node/4041374999)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4041375005",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.244552,
    "lng": -104.638885,
    "address": "Acero Avenue, Pueblo, CO 81004",
    "source": "OpenStreetMap (node/4041375005)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4041375052",
    "name": "7-Eleven",
    "category": "convenience",
    "lat": 38.220579,
    "lng": -104.644203,
    "address": "2727 South Prairie Avenue, Pueblo, CO 81005",
    "phone": "+1 719-564-0447",
    "url": "https://www.7-eleven.com/locations/co/pueblo/2727-south-prairie-13111",
    "source": "OpenStreetMap (node/4041375052)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4041375053",
    "name": "Conoco",
    "category": "convenience",
    "lat": 38.227276,
    "lng": -104.643326,
    "address": "South Prairie Avenue, Pueblo, CO 81005",
    "source": "OpenStreetMap (node/4041375053)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4043068526",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.331793,
    "lng": -104.745238,
    "address": "West Spaulding Avenue, Pueblo West, CO 81007",
    "source": "OpenStreetMap (node/4043068526)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-4043068646",
    "name": "KwikStop",
    "category": "convenience",
    "lat": 38.33259,
    "lng": -104.745053,
    "address": "West Spaulding Avenue, Pueblo West, CO 81007",
    "source": "OpenStreetMap (node/4043068646)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-5409829684",
    "name": "Boone Grocery & Hardware",
    "category": "convenience",
    "lat": 38.248148,
    "lng": -104.258833,
    "address": "410 Main Street, Boone",
    "hours_weekly": {
      "mon": [
        "08:00-17:00"
      ],
      "tue": [
        "08:00-17:00"
      ],
      "wed": [
        "08:00-17:00"
      ],
      "thu": [
        "08:00-17:00"
      ],
      "fri": [
        "08:00-17:00"
      ],
      "sat": [
        "08:00-17:00"
      ],
      "sun": [
        "08:00-17:00"
      ]
    },
    "source": "OpenStreetMap (node/5409829684)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-node-9330967204",
    "name": "Alta Convenience",
    "category": "convenience",
    "lat": 38.273125,
    "lng": -104.612008,
    "address": "West 7th Street, Pueblo, CO 81003",
    "source": "OpenStreetMap (node/9330967204)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-1079237907",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.32155,
    "lng": -104.702067,
    "address": "136 South Purcell Boulevard, Pueblo West, CO",
    "source": "OpenStreetMap (way/1079237907)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-1135823373",
    "name": "Conoco",
    "category": "convenience",
    "lat": 38.24434,
    "lng": -104.643387,
    "address": "1242 South Prairie Avenue, Pueblo 81004",
    "source": "OpenStreetMap (way/1135823373)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-1266766543",
    "name": "Katmando's",
    "category": "convenience",
    "lat": 38.322043,
    "lng": -104.817532,
    "address": "West Carrizo Springs Avenue, CO",
    "source": "OpenStreetMap (way/1266766543)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-224603771",
    "name": "Love's",
    "category": "convenience",
    "lat": 38.342235,
    "lng": -104.622958,
    "address": "6470 North Elizabeth Street, Pueblo, CO 81008",
    "source": "OpenStreetMap (way/224603771)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-264728293",
    "name": "Safeway",
    "category": "grocery",
    "lat": 38.325802,
    "lng": -104.697345,
    "address": "1017 North Market Plaza, Pueblo, CO 81007",
    "phone": "+1 719-547-2108",
    "url": "https://local.safeway.com/safeway/co/pueblo/1017-n-market-plaza.html",
    "source": "OpenStreetMap (way/264728293)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-439892311",
    "name": "Natural Grocers",
    "category": "grocery",
    "lat": 38.298935,
    "lng": -104.606822,
    "address": "101 West 29th Street, Pueblo, CO 81008",
    "hours_weekly": {
      "mon": [
        "08:30-21:06"
      ],
      "tue": [
        "08:30-21:06"
      ],
      "wed": [
        "08:00-21:06"
      ],
      "thu": [
        "08:30-21:06"
      ],
      "fri": [
        "08:30-21:06"
      ],
      "sat": [
        "08:30-21:06"
      ],
      "sun": [
        "09:00-19:35"
      ]
    },
    "phone": "+1-719-542-2411",
    "url": "https://www.naturalgrocers.com/store/pueblo",
    "source": "OpenStreetMap (way/439892311)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-439892313",
    "name": "King Soopers",
    "category": "grocery",
    "lat": 38.297492,
    "lng": -104.606537,
    "address": "102 West 29th Street, Pueblo, CO 81008",
    "hours_weekly": {
      "mon": [
        "05:00-24:00"
      ],
      "tue": [
        "05:00-24:00"
      ],
      "wed": [
        "05:00-24:00"
      ],
      "thu": [
        "05:00-24:00"
      ],
      "fri": [
        "05:00-24:00"
      ],
      "sat": [
        "05:00-24:00"
      ],
      "sun": [
        "05:00-24:00"
      ]
    },
    "phone": "+1-719-544-0390",
    "url": "https://www.kingsoopers.com/stores/details/620/00043",
    "source": "OpenStreetMap (way/439892313)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-466464064",
    "name": "Walmart Supercenter",
    "category": "grocery",
    "lat": 38.336395,
    "lng": -104.740068,
    "address": "78 North McCulloch Boulevard, Pueblo West, CO 81007",
    "hours_weekly": {
      "mon": [
        "00:00-24:00"
      ],
      "tue": [
        "00:00-24:00"
      ],
      "wed": [
        "00:00-24:00"
      ],
      "thu": [
        "00:00-24:00"
      ],
      "fri": [
        "00:00-24:00"
      ],
      "sat": [
        "00:00-24:00"
      ],
      "sun": [
        "00:00-24:00"
      ]
    },
    "phone": "+1 719-647-9861",
    "url": "https://www.walmart.com/store/3382-pueblo-west-co",
    "operator": "Walmart",
    "source": "OpenStreetMap (way/466464064)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-499816944",
    "name": "Fast Break",
    "category": "convenience",
    "lat": 37.962281,
    "lng": -104.79703,
    "address": "6654 State Highway 165, Colorado City, CO 81004",
    "source": "OpenStreetMap (way/499816944)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-499816958",
    "name": "Corner Store",
    "category": "convenience",
    "lat": 37.96137,
    "lng": -104.794169,
    "address": "8950 Abbey Road, Colorado City, CO 81004",
    "hours_weekly": {
      "mon": [
        "00:00-24:00"
      ],
      "tue": [
        "00:00-24:00"
      ],
      "wed": [
        "00:00-24:00"
      ],
      "thu": [
        "00:00-24:00"
      ],
      "fri": [
        "00:00-24:00"
      ],
      "sat": [
        "00:00-24:00"
      ],
      "sun": [
        "00:00-24:00"
      ]
    },
    "notes": "Convenience Store;Gas Station",
    "source": "OpenStreetMap (way/499816958)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-505568940",
    "name": "7-Eleven",
    "category": "convenience",
    "lat": 38.270551,
    "lng": -104.596404,
    "address": "804 East 4th Street, Pueblo, CO 81001",
    "hours_weekly": {
      "mon": [
        "00:00-24:00"
      ],
      "tue": [
        "00:00-24:00"
      ],
      "wed": [
        "00:00-24:00"
      ],
      "thu": [
        "00:00-24:00"
      ],
      "fri": [
        "00:00-24:00"
      ],
      "sat": [
        "00:00-24:00"
      ],
      "sun": [
        "00:00-24:00"
      ]
    },
    "phone": "+1 719-543-7265",
    "url": "https://www.7-eleven.com/locations/co/pueblo/804-e-4th-st-20638",
    "source": "OpenStreetMap (way/505568940)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-535378000",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.319854,
    "lng": -104.612845,
    "address": "Dillon Drive, Pueblo, CO 81008",
    "notes": "Operated by Loaf 'N Jug",
    "source": "OpenStreetMap (way/535378000)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-535378006",
    "name": "J R's Country Store",
    "category": "convenience",
    "lat": 38.321072,
    "lng": -104.617759,
    "address": "615 Eagleridge Boulevard, Pueblo, CO 81008",
    "hours_weekly": {
      "mon": [
        "00:00-24:00"
      ],
      "tue": [
        "00:00-24:00"
      ],
      "wed": [
        "00:00-24:00"
      ],
      "thu": [
        "00:00-24:00"
      ],
      "fri": [
        "00:00-24:00"
      ],
      "sat": [
        "00:00-24:00"
      ],
      "sun": [
        "00:00-24:00"
      ]
    },
    "operator": "J R's Country Store",
    "source": "OpenStreetMap (way/535378006)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-535379543",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.30889,
    "lng": -104.620024,
    "address": "905 West US Highway 50, Pueblo, CO 81008",
    "source": "OpenStreetMap (way/535379543)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-535379550",
    "name": "Circle K",
    "category": "convenience",
    "lat": 38.308324,
    "lng": -104.61681,
    "address": "601 West US Highway 50, Pueblo, CO 81008",
    "hours_weekly": {
      "mon": [
        "00:00-24:00"
      ],
      "tue": [
        "00:00-24:00"
      ],
      "wed": [
        "00:00-24:00"
      ],
      "thu": [
        "00:00-24:00"
      ],
      "fri": [
        "00:00-24:00"
      ],
      "sat": [
        "00:00-24:00"
      ],
      "sun": [
        "00:00-24:00"
      ]
    },
    "operator": "Corner Store",
    "source": "OpenStreetMap (way/535379550)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-535650928",
    "name": "7-Eleven",
    "category": "convenience",
    "lat": 38.306738,
    "lng": -104.614637,
    "address": "3522 North Elizabeth Street, Pueblo, CO 81008",
    "notes": "Operated by 7-Eleven",
    "source": "OpenStreetMap (way/535650928)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-535656814",
    "name": "Alta Convenience",
    "category": "convenience",
    "lat": 38.297107,
    "lng": -104.615997,
    "address": "2801 North Elizabeth Street, Pueblo, CO 81008",
    "notes": "Operated by Alta",
    "source": "OpenStreetMap (way/535656814)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-535686236",
    "name": "Loaf and Jug",
    "category": "convenience",
    "lat": 38.27461,
    "lng": -104.49248,
    "address": "32nd Lane, Baxter, CO 81006",
    "source": "OpenStreetMap (way/535686236)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-536454112",
    "name": "Walmart Supercenter",
    "category": "grocery",
    "lat": 38.313968,
    "lng": -104.609616,
    "address": "4200 Dillon Drive, Pueblo, CO 81008",
    "hours_weekly": {
      "mon": [
        "06:00-24:00"
      ],
      "tue": [
        "06:00-24:00"
      ],
      "wed": [
        "06:00-24:00"
      ],
      "thu": [
        "06:00-24:00"
      ],
      "fri": [
        "06:00-24:00"
      ],
      "sat": [
        "06:00-24:00"
      ],
      "sun": [
        "06:00-24:00"
      ]
    },
    "phone": "+1 719-545-6404",
    "url": "https://www.walmart.com/store/842-pueblo-co",
    "operator": "Walmart",
    "source": "OpenStreetMap (way/536454112)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-544400971",
    "name": "Albertsons",
    "category": "grocery",
    "lat": 38.310927,
    "lng": -104.627896,
    "address": "1601 US 50, Pueblo, CO 81008",
    "phone": "+1 719-543-5671",
    "url": "https://local.albertsons.com/co/pueblo/1601-hwy-50-w.html",
    "source": "OpenStreetMap (way/544400971)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-547529779",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.283193,
    "lng": -104.644771,
    "address": "Lambert Avenue, Pueblo, CO 81002",
    "source": "OpenStreetMap (way/547529779)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-591851971",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.271944,
    "lng": -104.572407,
    "address": "2119 East 4th Street, Pueblo, CO 81001",
    "hours_weekly": {
      "mon": [
        "00:00-24:00"
      ],
      "tue": [
        "00:00-24:00"
      ],
      "wed": [
        "00:00-24:00"
      ],
      "thu": [
        "00:00-24:00"
      ],
      "fri": [
        "00:00-24:00"
      ],
      "sat": [
        "00:00-24:00"
      ],
      "sun": [
        "00:00-24:00"
      ]
    },
    "source": "OpenStreetMap (way/591851971)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-659620782",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.267354,
    "lng": -104.606481,
    "address": "Hector Garcia Place, Pueblo, CO 81003",
    "source": "OpenStreetMap (way/659620782)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-682492454",
    "name": "Walmart Supercenter",
    "category": "grocery",
    "lat": 38.232249,
    "lng": -104.665013,
    "address": "4080 West Northern Avenue, Pueblo, CO 81005",
    "hours_weekly": {
      "mon": [
        "06:00-24:00"
      ],
      "tue": [
        "06:00-24:00"
      ],
      "wed": [
        "06:00-24:00"
      ],
      "thu": [
        "06:00-24:00"
      ],
      "fri": [
        "06:00-24:00"
      ],
      "sat": [
        "06:00-24:00"
      ],
      "sun": [
        "06:00-24:00"
      ]
    },
    "phone": "+1 719-561-8495",
    "url": "https://www.walmart.com/store/1001-pueblo-co",
    "operator": "Walmart",
    "source": "OpenStreetMap (way/682492454)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-682492473",
    "name": "Walmart Neighborhood Market",
    "category": "grocery",
    "lat": 38.219895,
    "lng": -104.641579,
    "address": "2730 South Prairie Avenue, Pueblo, CO 81005",
    "hours_weekly": {
      "mon": [
        "06:00-23:00"
      ],
      "tue": [
        "06:00-23:00"
      ],
      "wed": [
        "06:00-23:00"
      ],
      "thu": [
        "06:00-23:00"
      ],
      "fri": [
        "06:00-23:00"
      ],
      "sat": [
        "06:00-23:00"
      ],
      "sun": [
        "06:00-23:00"
      ]
    },
    "phone": "+1 719-696-6149",
    "url": "https://www.walmart.com/store/5828/pueblo-co",
    "operator": "Walmart",
    "source": "OpenStreetMap (way/682492473)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-946612229",
    "name": "Safeway",
    "category": "grocery",
    "lat": 38.24485,
    "lng": -104.644309,
    "address": "1231 South Prairie Avenue, Pueblo, CO 81005",
    "hours_weekly": {
      "mon": [
        "06:00-23:00"
      ],
      "tue": [
        "06:00-23:00"
      ],
      "wed": [
        "06:00-23:00"
      ],
      "thu": [
        "06:00-23:00"
      ],
      "fri": [
        "06:00-23:00"
      ],
      "sat": [
        "06:00-23:00"
      ],
      "sun": [
        "06:00-23:00"
      ]
    },
    "phone": "+1-719-561-1234",
    "url": "https://local.safeway.com/safeway/co/pueblo/1231-s-prairie-ave.html",
    "source": "OpenStreetMap (way/946612229)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-946612238",
    "name": "King Soopers",
    "category": "grocery",
    "lat": 38.242781,
    "lng": -104.645865,
    "address": "3050 West Northern Avenue, Pueblo, CO 81005",
    "hours_weekly": {
      "mon": [
        "05:00-24:00"
      ],
      "tue": [
        "05:00-24:00"
      ],
      "wed": [
        "05:00-24:00"
      ],
      "thu": [
        "05:00-24:00"
      ],
      "fri": [
        "05:00-24:00"
      ],
      "sat": [
        "05:00-24:00"
      ],
      "sun": [
        "05:00-24:00"
      ]
    },
    "phone": "+1-719-564-0590",
    "url": "https://www.kingsoopers.com/stores/details/620/00012",
    "source": "OpenStreetMap (way/946612238)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-946614791",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.287191,
    "lng": -104.59641,
    "address": "1002 Bonforte Boulevard, Pueblo, CO 81001",
    "source": "OpenStreetMap (way/946614791)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-946614803",
    "name": "Save-A-Lot",
    "category": "grocery",
    "lat": 38.288387,
    "lng": -104.594668,
    "address": "1110 Bonforte Boulevard, Pueblo, CO 81001",
    "hours_weekly": {
      "mon": [
        "08:00-21:00"
      ],
      "tue": [
        "08:00-21:00"
      ],
      "wed": [
        "08:00-21:00"
      ],
      "thu": [
        "08:00-21:00"
      ],
      "fri": [
        "08:00-21:00"
      ],
      "sat": [
        "08:00-21:00"
      ],
      "sun": [
        "08:00-21:00"
      ]
    },
    "phone": "+1-719-544-6057",
    "url": "https://savealot.com/grocery-stores/pueblo-81001-23844/",
    "source": "OpenStreetMap (way/946614803)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-947245256",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.233804,
    "lng": -104.666376,
    "address": "4125 Thames Drive, Pueblo, CO 81005",
    "source": "OpenStreetMap (way/947245256)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-971896407",
    "name": "Musso Farms",
    "category": "farm",
    "lat": 38.243926,
    "lng": -104.461243,
    "address": "35779 Hillside Road, Pueblo, CO 81006",
    "hours_weekly": {
      "mon": [
        "08:00-18:00"
      ],
      "tue": [
        "08:00-18:00"
      ],
      "wed": [
        "08:00-18:00"
      ],
      "thu": [
        "08:00-18:00"
      ],
      "fri": [
        "08:00-18:00"
      ],
      "sat": [
        "08:00-18:00"
      ]
    },
    "accepts_snap": true,
    "phone": "+1 719-948-3581",
    "url": "https://www.mussofarmschileroom.com/",
    "notes": "surcharge for using cards",
    "source": "OpenStreetMap (way/971896407)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "osm-way-974172860",
    "name": "Loaf 'N Jug",
    "category": "convenience",
    "lat": 38.284965,
    "lng": -104.572577,
    "address": "2120 Oakshire Lane, Pueblo, CO 81001",
    "source": "OpenStreetMap (way/974172860)",
    "last_verified": "2026-05-20"
  },
  {
    "id": "plentiful-agape-fellowship-church-925bb133",
    "name": "Agape Fellowship Church",
    "category": "pantry",
    "lat": 38.25376,
    "lng": -104.626774,
    "address": "611 Broadway Ave., Pueblo, CO 81004",
    "url": "https://directory.plentiful.org/colorado/pueblo/agape-fellowship-church-925bb133",
    "notes": "Agape Fellowship Church. in Pueblo, CO. Hours and directions available.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-assistance-league-pueblo-services-7754e3e3",
    "name": "Assistance League-Pueblo Services",
    "category": "pantry",
    "lat": 38.246826,
    "lng": -104.662071,
    "address": "1112 Pueblo Blvd, Pueblo, CO 81005",
    "phone": "(719) 544-1528",
    "url": "https://directory.plentiful.org/colorado/pueblo/assistance-league-pueblo-services-7754e3e3",
    "notes": "Assistance League-Pueblo Services. in Pueblo, CO. Phone: (719) 544-1528.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-bessemer-mobile-food-pantry-58874d63",
    "name": "Bessemer Mobile Food Pantry",
    "category": "pantry",
    "lat": 38.237869,
    "lng": -104.612428,
    "address": "215 Canal St, Pueblo, CO 81004",
    "url": "https://directory.plentiful.org/colorado/pueblo/bessemer-mobile-food-pantry-58874d63",
    "notes": "Bessemer Mobile Food Pantry. in Pueblo, CO.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-bgcc-pueblo-pantry-plentiful-4069",
    "name": "BGCC Pueblo Pantry",
    "category": "pantry",
    "lat": 38.274686,
    "lng": -104.590266,
    "address": "1230 E 8th St, Pueblo, CO 81001",
    "hours_weekly": {
      "thu": [
        "11:00 AM - 2:00 PM"
      ]
    },
    "phone": "(719) 470-1004",
    "url": "https://directory.plentiful.org/colorado/pueblo/bgcc-pueblo-pantry-plentiful-4069",
    "notes": "BGCC Pueblo Pantry. in Pueblo, CO. Phone: (719) 470-1004.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-blessing-box-216-w-routt-plentiful-1454",
    "name": "Blessing Box - 216 W Routt",
    "category": "pantry",
    "lat": 38.25902,
    "lng": -104.625612,
    "address": "216 W Routt Ave, Pueblo, CO 81004",
    "hours_weekly": {
      "tue": [
        "8:00 AM - 2:00 PM"
      ]
    },
    "phone": "(800) 748-2074",
    "url": "https://directory.plentiful.org/colorado/pueblo/blessing-box-216-w-routt-plentiful-1454",
    "notes": "Blessing Box - 216 W Routt. in Pueblo, CO. Phone: (800) 748-2074.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-care-and-share-food-bank-for-southern-colorado-main-location-4a362e63",
    "name": "Care and Share Food Bank for Southern Colorado - Main Location",
    "category": "pantry",
    "lat": 38.209461,
    "lng": -104.627381,
    "address": "100 Greenhorn Dr #100, Pueblo, CO 81004",
    "url": "https://directory.plentiful.org/colorado/pueblo/care-and-share-food-bank-for-southern-colorado-main-location-4a362e63",
    "notes": "Care and Share Food Bank for Southern Colorado - Main Location. in Pueblo, CO. Hours and directions available.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-center-toward-self-reliance-1c29edf8",
    "name": "Center Toward Self-Reliance",
    "category": "pantry",
    "lat": 38.274091,
    "lng": -104.6197,
    "address": "901 W. 8th St., Pueblo, CO 81003",
    "phone": "(719) 546-1271",
    "url": "https://directory.plentiful.org/colorado/pueblo/center-toward-self-reliance-1c29edf8",
    "notes": "Center Toward Self-Reliance. in Pueblo, CO. Phone: (719) 546-1271.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-colorado-division-of-housing-food-distribution-center-5448eb74",
    "name": "Colorado Division Of Housing - Food Distribution Center",
    "category": "pantry",
    "lat": 38.262858,
    "lng": -104.617193,
    "address": "132 W B St, Pueblo, CO 81003",
    "url": "https://directory.plentiful.org/colorado/pueblo/colorado-division-of-housing-food-distribution-center-5448eb74",
    "notes": "Colorado Division Of Housing - Food Distribution Center. in Pueblo, CO.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-compassion-care-pueblo-caba5d25",
    "name": "Compassion Care- Pueblo",
    "category": "pantry",
    "lat": 38.247716,
    "lng": -104.613751,
    "address": "1102 E. Abriendo Ave., Pueblo, CO 81004",
    "phone": "(719) 423-9138",
    "url": "https://directory.plentiful.org/colorado/pueblo/compassion-care-pueblo-caba5d25",
    "notes": "Compassion Care- Pueblo. in Pueblo, CO. Phone: (719) 423-9138.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-cornerstone-assembly-of-god-pueblo-e68b65ea",
    "name": "Cornerstone Assembly of God Pueblo",
    "category": "pantry",
    "lat": 38.254816,
    "lng": -104.633727,
    "address": "1902 St. Clair Ave., Pueblo, CO 81004",
    "phone": "(719) 542-4133",
    "url": "https://directory.plentiful.org/colorado/pueblo/cornerstone-assembly-of-god-pueblo-e68b65ea",
    "notes": "Cornerstone Assembly of God Pueblo. in Pueblo, CO. Phone: (719) 542-4133.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-edible-planet-food-distribution-center-71b7a0fe",
    "name": "Edible Planet - Food Distribution Center",
    "category": "pantry",
    "lat": 38.264913,
    "lng": -104.565793,
    "address": "414 Booth Ave, Pueblo, CO 81001",
    "url": "https://directory.plentiful.org/colorado/pueblo/edible-planet-food-distribution-center-71b7a0fe",
    "notes": "Edible Planet - Food Distribution Center. in Pueblo, CO.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-eva-r-baca-elementary-school-52dc3901",
    "name": "Eva R Baca Elementary School",
    "category": "pantry",
    "lat": 38.283411,
    "lng": -104.579346,
    "address": "2800 East 17th St, Pueblo, CO 81001",
    "url": "https://directory.plentiful.org/colorado/pueblo/eva-r-baca-elementary-school-52dc3901",
    "notes": "Eva R Baca Elementary School. in Pueblo, CO.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-first-congregational-united-church-of-christ-pueblo-plentiful-4247",
    "name": "First Congregational United Church of Christ- Pueblo",
    "category": "pantry",
    "lat": 38.260184,
    "lng": -104.624609,
    "address": "228 W Evans Ave, Pueblo, CO 81004",
    "hours_weekly": {
      "sun": [
        "9:00 AM - 12:00 PM"
      ]
    },
    "phone": "(719) 544-1892",
    "url": "https://directory.plentiful.org/colorado/pueblo/first-congregational-united-church-of-christ-pueblo-plentiful-4247",
    "notes": "First Congregational United Church of Christ- Pueblo. in Pueblo, CO. Phone: (719) 544-1892.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-foodbank-of-eastside-neighbor-s-council-fde35382",
    "name": "Foodbank of Eastside Neighbor's Council",
    "category": "pantry",
    "lat": 38.270611,
    "lng": -104.606116,
    "address": "224 E 4th St, Pueblo, CO 81003",
    "url": "https://directory.plentiful.org/colorado/pueblo/foodbank-of-eastside-neighbor-s-council-fde35382",
    "notes": "Foodbank of Eastside Neighbor's Council. in Pueblo, CO.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-full-force-ministries-food-pantry-cf58c38d",
    "name": "Full Force Ministries Food Pantry",
    "category": "pantry",
    "lat": 38.247706,
    "lng": -104.619755,
    "address": "1101 Cedar St., Pueblo, CO 81004",
    "url": "https://directory.plentiful.org/colorado/pueblo/full-force-ministries-food-pantry-cf58c38d",
    "notes": "Full Force Ministries Food Pantry. in Pueblo, CO.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-lynn-gardens-baptist-church-d9ee705e",
    "name": "Lynn Gardens Baptist Church",
    "category": "pantry",
    "lat": 38.223992,
    "lng": -104.656767,
    "address": "3804 W. Pueblo Blvd., Pueblo, CO 81005",
    "url": "https://directory.plentiful.org/colorado/pueblo/lynn-gardens-baptist-church-d9ee705e",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-minnequa-vfw-post-3641-9faa99be",
    "name": "Minnequa VFW Post 3641",
    "category": "pantry",
    "lat": 38.270809,
    "lng": -104.597789,
    "address": "724 E. 4th St., Pueblo, CO 81001",
    "phone": "(719) 406-5247",
    "url": "https://directory.plentiful.org/colorado/pueblo/minnequa-vfw-post-3641-9faa99be",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-mt-carmel-veteran-center-of-pueblo-76b970d4",
    "name": "Mt Carmel Veteran Center of Pueblo",
    "category": "pantry",
    "lat": 38.234119,
    "lng": -104.62075,
    "address": "1925 E. Orman Ave., Pueblo, CO 81004",
    "phone": "(719) 309-4719",
    "url": "https://directory.plentiful.org/colorado/pueblo/mt-carmel-veteran-center-of-pueblo-76b970d4",
    "notes": "Mt Carmel Veteran Center of Pueblo. in Pueblo, CO. Phone: (719) 309-4719.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-new-heights-baptist-church-35755919",
    "name": "New Heights Baptist Church",
    "category": "pantry",
    "lat": 38.304889,
    "lng": -104.63527,
    "address": "3304 Baltimore Ave., Pueblo, CO 81008",
    "url": "https://directory.plentiful.org/colorado/pueblo/new-heights-baptist-church-35755919",
    "notes": "New Heights Baptist Church. in Pueblo, CO. Hours and directions available.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-praise-assembly-of-god-food-pantry-2118f856",
    "name": "Praise Assembly of God - Food Pantry",
    "category": "pantry",
    "lat": 38.285559,
    "lng": -104.573368,
    "address": "2000 Troy Avenue, Pueblo, CO 81001",
    "url": "https://directory.plentiful.org/colorado/pueblo/praise-assembly-of-god-food-pantry-2118f856",
    "notes": "Praise Assembly of God - Food Pantry. in Pueblo, CO.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-pueblo-community-college-mobile-pantry-stop-e0de86e7",
    "name": "Pueblo Community College - Mobile Pantry Stop",
    "category": "pantry",
    "lat": 38.263186,
    "lng": -104.637172,
    "address": "Pueblo Community College",
    "url": "https://directory.plentiful.org/colorado/pueblo/pueblo-community-college-mobile-pantry-stop-e0de86e7",
    "notes": "Pueblo Community College - Mobile Pantry Stop. in Pueblo, CO. Hours and directions available.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-pueblo-community-college-school-pantry-cdc32119",
    "name": "Pueblo Community College - School Pantry",
    "category": "pantry",
    "lat": 38.263186,
    "lng": -104.637172,
    "address": "Pueblo Community College",
    "url": "https://directory.plentiful.org/colorado/pueblo/pueblo-community-college-school-pantry-cdc32119",
    "notes": "Pueblo Community College - School Pantry. in Pueblo, CO. Hours and directions available.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-pueblo-community-soup-kitchen-1bc98af5",
    "name": "Pueblo Community Soup Kitchen",
    "category": "meal_site",
    "lat": 38.273296,
    "lng": -104.612059,
    "address": "422 W. 7th St., Pueblo, CO 81003",
    "phone": "(719) 545-6540",
    "url": "https://directory.plentiful.org/colorado/pueblo/pueblo-community-soup-kitchen-1bc98af5",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-pueblo-community-soup-kitchen-plentiful-3195",
    "name": "Pueblo Community Soup Kitchen",
    "category": "meal_site",
    "lat": 38.273296,
    "lng": -104.612059,
    "address": "422 W. 7th Street, Pueblo, CO 81003",
    "hours_weekly": {
      "mon": [
        "10:30 AM - 12:00 PM",
        "8:30 AM - 9:30 AM"
      ],
      "tue": [
        "10:30 AM - 12:00 PM",
        "8:30 AM - 9:30 AM"
      ],
      "wed": [
        "10:30 AM - 12:00 PM",
        "8:30 AM - 9:30 AM"
      ],
      "thu": [
        "10:30 AM - 12:00 PM",
        "8:30 AM - 9:30 AM"
      ],
      "fri": [
        "10:30 AM - 12:00 PM",
        "8:30 AM - 9:30 AM"
      ],
      "sat": [
        "10:30 AM - 12:00 PM",
        "8:30 AM - 9:30 AM"
      ]
    },
    "phone": "(719) 545-6540",
    "url": "https://directory.plentiful.org/colorado/pueblo/pueblo-community-soup-kitchen-plentiful-3195",
    "notes": "Pueblo Community Soup Kitchen. in Pueblo, CO. Phone: (719) 545-6540.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-pueblo-cooperative-care-center-97ec4eda",
    "name": "Pueblo Cooperative Care Center",
    "category": "pantry",
    "lat": 38.274237,
    "lng": -104.610622,
    "address": "326 West 8th Street, Pueblo, CO 81003",
    "url": "https://directory.plentiful.org/colorado/pueblo/pueblo-cooperative-care-center-97ec4eda",
    "notes": "Pueblo Cooperative Care Center. in Pueblo, CO. Hours and directions available.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-pueblo-cooperative-care-center-plentiful-3140",
    "name": "Pueblo Cooperative Care Center",
    "category": "pantry",
    "lat": 38.274237,
    "lng": -104.610622,
    "address": "326 W 8th St, Pueblo, CO 81003",
    "hours_weekly": {
      "mon": [
        "9:00 AM - 1:00 PM"
      ],
      "tue": [
        "9:00 AM - 1:00 PM"
      ],
      "wed": [
        "9:00 AM - 1:00 PM"
      ],
      "thu": [
        "9:00 AM - 1:00 PM"
      ]
    },
    "phone": "(719) 543-7484",
    "url": "https://directory.plentiful.org/colorado/pueblo/pueblo-cooperative-care-center-plentiful-3140",
    "notes": "Pueblo Cooperative Care Center. in Pueblo, CO. Phone: (719) 543-7484.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-pueblo-county-hhs-c01bc9c1",
    "name": "Pueblo County HHS",
    "category": "pantry",
    "lat": 38.272001,
    "lng": -104.563807,
    "address": "2631 East 4th Street, Pueblo, CO 81001",
    "phone": "(719) 583-6199",
    "url": "https://directory.plentiful.org/colorado/pueblo/pueblo-county-hhs-c01bc9c1",
    "notes": "Pueblo County HHS. in Pueblo, CO. Phone: (719) 583-6199.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-pueblo-county-usda-food-distribution-plentiful-3149",
    "name": "Pueblo County USDA Food Distribution",
    "category": "pantry",
    "lat": 38.272001,
    "lng": -104.563807,
    "address": "2631 E 4th St, Pueblo, CO 81001",
    "hours_weekly": {
      "mon": [
        "7:30 AM - 3:15 PM"
      ],
      "tue": [
        "7:30 AM - 3:15 PM"
      ],
      "wed": [
        "7:30 AM - 3:15 PM"
      ],
      "thu": [
        "7:30 AM - 3:15 PM"
      ],
      "fri": [
        "7:30 AM - 3:15 PM"
      ]
    },
    "phone": "(719) 583-6199",
    "url": "https://directory.plentiful.org/colorado/pueblo/pueblo-county-usda-food-distribution-plentiful-3149",
    "notes": "Pueblo County USDA Food Distribution. in Pueblo, CO. Phone: (719) 583-6199.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-pueblo-united-3d8ce244",
    "name": "Pueblo United",
    "category": "pantry",
    "lat": 38.271856,
    "lng": -104.599463,
    "address": "615 E. 5th St., Pueblo, CO 81001",
    "phone": "(719) 696-8586",
    "url": "https://directory.plentiful.org/colorado/pueblo/pueblo-united-3d8ce244",
    "notes": "Pueblo United. in Pueblo, CO. Phone: (719) 696-8586.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-rmser-empowerment-center-plentiful-3072",
    "name": "RMSER Empowerment Center",
    "category": "pantry",
    "lat": 38.254427,
    "lng": -104.620381,
    "address": "330 Lake Ave, Pueblo, CO 81004",
    "hours_weekly": {
      "wed": [
        "4:00 PM - 6:00 PM"
      ],
      "fri": [
        "4:00 PM - 6:00 PM"
      ]
    },
    "phone": "(800) 748-2074",
    "url": "https://directory.plentiful.org/colorado/pueblo/rmser-empowerment-center-plentiful-3072",
    "notes": "RMSER Empowerment Center. in Pueblo, CO. Phone: (800) 748-2074.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-salvation-army-pueblo-plentiful-3190",
    "name": "Salvation Army- Pueblo",
    "category": "pantry",
    "lat": 38.260216,
    "lng": -104.644065,
    "address": "401 S Prairie Ave, Pueblo, CO 81005",
    "hours_weekly": {
      "tue": [
        "10:00 AM - 12:00 PM"
      ],
      "wed": [
        "10:00 AM - 12:00 PM"
      ],
      "thu": [
        "10:00 AM - 12:00 PM"
      ]
    },
    "phone": "(719) 543-3656",
    "url": "https://directory.plentiful.org/colorado/pueblo/salvation-army-pueblo-plentiful-3190",
    "notes": "Salvation Army- Pueblo. in Pueblo, CO. Phone: (719) 543-3656.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-senior-resource-development-agency-pueblo-inc-plentiful-3197",
    "name": "Senior Resource Development Agency, Pueblo Inc.",
    "category": "pantry",
    "lat": 38.266428,
    "lng": -104.610567,
    "address": "230 N Union Ave, Pueblo, CO 81003",
    "hours_weekly": {
      "mon": [
        "11:00 AM - 12:30 PM"
      ],
      "tue": [
        "11:00 AM - 12:30 PM"
      ],
      "wed": [
        "11:00 AM - 12:30 PM"
      ],
      "thu": [
        "11:00 AM - 12:30 PM"
      ],
      "fri": [
        "11:00 AM - 12:30 PM"
      ]
    },
    "phone": "(719) 543-0100",
    "url": "https://directory.plentiful.org/colorado/pueblo/senior-resource-development-agency-pueblo-inc-plentiful-3197",
    "notes": "Senior Resource Development Agency, Pueblo Inc.. in Pueblo, CO. Phone: (719) 543-0100.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-senior-towers-mobile-market-19a75a56",
    "name": "Senior Towers - Mobile Market",
    "category": "pantry",
    "lat": 38.265162,
    "lng": -104.610623,
    "address": "165 Central Main St., Pueblo, CO 81003",
    "phone": "(719) 296-6995",
    "url": "https://directory.plentiful.org/colorado/pueblo/senior-towers-mobile-market-19a75a56",
    "notes": "Senior Towers - Mobile Market. in Pueblo, CO. Phone: (719) 296-6995.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-st-anne-s-catholic-church-37512aae",
    "name": "St. Anne's Catholic Church",
    "category": "pantry",
    "lat": 38.279561,
    "lng": -104.562587,
    "address": "2701 E. 12th St., Pueblo, CO 81001",
    "url": "https://directory.plentiful.org/colorado/pueblo/st-anne-s-catholic-church-37512aae",
    "notes": "St. Anne's Catholic Church. in Pueblo, CO.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-steel-city-fellowship-2d4c6ff3",
    "name": "Steel City Fellowship",
    "category": "pantry",
    "lat": 38.290574,
    "lng": -104.596121,
    "address": "1401 Jerry Murphy Rd., Pueblo, CO 81001",
    "phone": "(719) 350-5001",
    "url": "https://directory.plentiful.org/colorado/pueblo/steel-city-fellowship-2d4c6ff3",
    "notes": "Steel City Fellowship. in Pueblo, CO. Phone: (719) 350-5001.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-the-avenue-church-plentiful-3200",
    "name": "The Avenue Church",
    "category": "pantry",
    "lat": 38.258422,
    "lng": -104.647055,
    "address": "3030 Thatcher Ave, Pueblo, CO 81005",
    "hours_weekly": {
      "sat": [
        "9:00 AM - 11:30 AM"
      ]
    },
    "phone": "(719) 561-1512",
    "url": "https://directory.plentiful.org/colorado/pueblo/the-avenue-church-plentiful-3200",
    "notes": "The Avenue Church. in Pueblo, CO. Phone: (719) 561-1512.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-the-pueblo-shelter-safeside-recovery-plentiful-4265",
    "name": "The Pueblo Shelter/SafeSide Recovery",
    "category": "pantry",
    "lat": 38.270682,
    "lng": -104.616821,
    "address": "728 W 4th St, Pueblo, CO 81003",
    "hours_weekly": {
      "mon": [
        "4:30 PM - 5:00 PM"
      ],
      "tue": [
        "4:30 PM - 5:00 PM"
      ],
      "wed": [
        "4:30 PM - 5:00 PM"
      ],
      "thu": [
        "4:30 PM - 5:00 PM"
      ],
      "fri": [
        "2:00 PM - 4:00 PM",
        "4:30 PM - 5:00 PM"
      ],
      "sat": [
        "4:30 PM - 5:00 PM"
      ],
      "sun": [
        "4:30 PM - 5:00 PM"
      ]
    },
    "phone": "(719) 924-8413",
    "url": "https://directory.plentiful.org/colorado/pueblo/the-pueblo-shelter-safeside-recovery-plentiful-4265",
    "notes": "The Pueblo Shelter/SafeSide Recovery. in Pueblo, CO. Phone: (719) 924-8413.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  },
  {
    "id": "plentiful-victory-life-ministries-a24917c0",
    "name": "Victory Life Ministries",
    "category": "pantry",
    "lat": 38.240536,
    "lng": -104.638127,
    "address": "2315 Sprague Ave, Pueblo, CO 81004",
    "url": "https://directory.plentiful.org/colorado/pueblo/victory-life-ministries-a24917c0",
    "notes": "Victory Life Ministries. in Pueblo, CO.",
    "source": "directory.plentiful.org/colorado/pueblo",
    "last_verified": "2026-05-14"
  }
];
